---
- hosts: master4
  remote_user: sevone
  tasks:
  - name: Get list of Pods by kube
    shell: kubectl get pods
    register: out
  - debug: var=out.stdout_lines

- hosts: master4
  remote_user: sevone
  tasks:
  - name: Get list of Pods by sdi
    command: sdi-cli pods
    register: out

  - debug: var=out.stdout_lines
