---
- hosts: master4
  remote_user: sevone
  tasks:
  - name: Teardown Cluster usind sdi-cli
    shell: /usr/bin/sdi-cli cluster teardown --delete-data -f
    register: out
  - debug: var=out.stdout_lines

  - name: Get list of Nodes by sdi
    command: sdi-cli nodes
    register: out
  - debug: var=out.stdout_lines
